// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Uc_10_Wendel_StudyCards.Data;

#nullable disable

namespace Uc_10_Wendel_StudyCards.Migrations
{
    [DbContext(typeof(Uc_10_Wendel_StudyCardsContext))]
    partial class Uc_10_Wendel_StudyCardsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Uc_10_Wendel_StudyCards.Models.Baralho", b =>
                {
                    b.Property<int>("BaralhoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BaralhoId"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImagemUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MateriaId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("BaralhoId");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("MateriaId");

                    b.ToTable("Baralho");
                });

            modelBuilder.Entity("Uc_10_Wendel_StudyCards.Models.Card", b =>
                {
                    b.Property<int>("CardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CardId"));

                    b.Property<int>("BaralhoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<int>("DificuldadeId")
                        .HasColumnType("int");

                    b.Property<string>("Pergunta")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Resposta")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("CardId");

                    b.HasIndex("BaralhoId");

                    b.HasIndex("DificuldadeId");

                    b.ToTable("Card");
                });

            modelBuilder.Entity("Uc_10_Wendel_StudyCards.Models.Categoria", b =>
                {
                    b.Property<int>("CategoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoriaId"));

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("CategoriaId");

                    b.ToTable("Categoria");
                });

            modelBuilder.Entity("Uc_10_Wendel_StudyCards.Models.Dificuldade", b =>
                {
                    b.Property<int>("DificuldadeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DificuldadeId"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("DificuldadeId");

                    b.ToTable("Dificuldade");
                });

            modelBuilder.Entity("Uc_10_Wendel_StudyCards.Models.Materia", b =>
                {
                    b.Property<int>("MateriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MateriaId"));

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("MateriaId");

                    b.ToTable("Materia");
                });

            modelBuilder.Entity("Uc_10_Wendel_StudyCards.Models.Baralho", b =>
                {
                    b.HasOne("Uc_10_Wendel_StudyCards.Models.Categoria", "Categoria")
                        .WithMany("Baralhos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Uc_10_Wendel_StudyCards.Models.Materia", "Materia")
                        .WithMany("Baralhos")
                        .HasForeignKey("MateriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Materia");
                });

            modelBuilder.Entity("Uc_10_Wendel_StudyCards.Models.Card", b =>
                {
                    b.HasOne("Uc_10_Wendel_StudyCards.Models.Baralho", "Baralho")
                        .WithMany("Cards")
                        .HasForeignKey("BaralhoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Uc_10_Wendel_StudyCards.Models.Dificuldade", "Dificuldade")
                        .WithMany("Cards")
                        .HasForeignKey("DificuldadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Baralho");

                    b.Navigation("Dificuldade");
                });

            modelBuilder.Entity("Uc_10_Wendel_StudyCards.Models.Baralho", b =>
                {
                    b.Navigation("Cards");
                });

            modelBuilder.Entity("Uc_10_Wendel_StudyCards.Models.Categoria", b =>
                {
                    b.Navigation("Baralhos");
                });

            modelBuilder.Entity("Uc_10_Wendel_StudyCards.Models.Dificuldade", b =>
                {
                    b.Navigation("Cards");
                });

            modelBuilder.Entity("Uc_10_Wendel_StudyCards.Models.Materia", b =>
                {
                    b.Navigation("Baralhos");
                });
#pragma warning restore 612, 618
        }
    }
}
